import importlib.util
ori_module_spec = importlib.util.spec_from_file_location('ori_module', '.\\examples\\assign4\\law.py')
test_module_spec = importlib.util.spec_from_file_location('test_module', '.\\updated\\assign4\\law.py')
ori_module = importlib.util.module_from_spec(ori_module_spec)
test_module = importlib.util.module_from_spec(test_module_spec)
ori_module_spec.loader.exec_module(ori_module)
test_module_spec.loader.exec_module(test_module)

def test_bar1():
    assert ori_module.bar1(0, 0, 1, 0) == test_module.bar1(0, 0, 1, 0)
    assert ori_module.bar1(0, 0, 0, 0) == test_module.bar1(0, 0, 0, 0)
    assert ori_module.bar1(-1, 0, 0, 0) == test_module.bar1(-1, 0, 0, 0)
    assert ori_module.bar1(-1, 0, 0, 1) == test_module.bar1(-1, 0, 0, 1)
    assert ori_module.bar1(1, 0, 0, 0) == test_module.bar1(1, 0, 0, 0)
    assert ori_module.bar1(1, 0, 1, 0) == test_module.bar1(1, 0, 1, 0)
def test_bar2():
    assert ori_module.bar2(0, 0, 1) == test_module.bar2(0, 0, 1)
    assert ori_module.bar2(0, 0, 0) == test_module.bar2(0, 0, 0)
    assert ori_module.bar2(-1, 0, 0) == test_module.bar2(-1, 0, 0)
    assert ori_module.bar2(-1, 0, 0) == test_module.bar2(-1, 0, 0)
    assert ori_module.bar2(1, 0, 0) == test_module.bar2(1, 0, 0)
    assert ori_module.bar2(1, 0, 1) == test_module.bar2(1, 0, 1)
    assert ori_module.bar2(None, 0, 0) == test_module.bar2(None, 0, 0)
    assert ori_module.bar2(-1, 0, -1) == test_module.bar2(-1, 0, -1)
    assert ori_module.bar2(-1, 0, 1) == test_module.bar2(-1, 0, 1)
    assert ori_module.bar2(0, 2, 1) == test_module.bar2(0, 2, 1)
